name: Test1




on:
  workflow_dispatch:
    inputs:

jobs:
  listfiles:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list
      run: |
        ls ${GITHUB_WORKSPACE}/
        sudo apt install nodejs
        cd ${GITHUB_WORKSPACE}/gd-utils
        pm2-runtime start server.js
